# Generated by Django 6.0.3 on 2026-06-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('PRODUCT', 'Product Based'), ('SUBCATEGORY', 'Subcategory Based'), ('CATEGORY', 'Category Based')], max_length=20),
        ),
    ]
