# Generated by Django 6.0.3 on 2026-04-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashio_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
