# Generated by Django 6.0.3 on 2026-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_referral_code_user_referral_reward_given_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
