# Generated by Django 6.0.3 on 2026-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_cancel_comment_orderitem_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
