# Generated by Django 6.0.3 on 2026-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
