# Generated by Django 6.0.3 on 2026-06-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_returnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='is_admin_seen',
        ),
    ]
