# Generated by Django 6.0.3 on 2026-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_returnrequest_is_admin_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], max_length=100),
        ),
    ]
