# Generated by Django 6.0.3 on 2026-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
