# Generated by Django 6.0.3 on 2026-07-01 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_coupon_couponusage'),
        ('orders', '0015_orderitem_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.coupon'),
        ),
    ]
